[project]
name = "escape-room-apocalypse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qrcode>=8.2",
    "streamlit>=1.51.0",
]
